import enum


class TaskStatus(str, enum.Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    IN_WORK = "IN_WORK"
    FINISHED = "FINISHED"
    ERROR = "ERROR"


class TaskTypes(str, enum.Enum):
    DOWNLOAD_VIDEO = "DOWNLOAD_VIDEO"
    EXTRACT_VIDEO_DESCRIPTION = "EXTRACT_VIDEO_DESCRIPTION"
    GENERATE_IMAGE_FROM_TEXT = "GENERATE_IMAGE_FROM_TEXT"
