"""added TaskDataTemplate columns and updated TaskData columns for better data storing

Revision ID: 1c683eedbe18
Revises: 5dc2afedb93c
Create Date: 2024-03-24 14:54:13.940628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1c683eedbe18'
down_revision: Union[str, None] = '5dc2afedb93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_data', sa.Column('field_value_str', sa.TEXT(), nullable=True))
    op.add_column('task_data', sa.Column('field_value_int', sa.Integer(), nullable=True))
    op.add_column('task_data', sa.Column('field_value_float', sa.Float(), nullable=True))
    op.add_column('task_data', sa.Column('field_value_datetime', sa.DateTime(), nullable=True))

    op.drop_column('task_data', 'field_value')
    op.add_column('task_data_template', sa.Column('default_value', sa.TEXT(), nullable=True))
    op.add_column('task_data_template', sa.Column('is_required', sa.Boolean(), nullable=True, ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_data_template', 'is_required')
    op.drop_column('task_data_template', 'default_value')
    op.add_column('task_data', sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_column('task_data', 'field_value_datetime')
    op.drop_column('task_data', 'field_value_float')
    op.drop_column('task_data', 'field_value_int')
    op.drop_column('task_data', 'field_value_str')
    # ### end Alembic commands ###
