"""added task data and template data tables, removed task type from name field in task_type table

Revision ID: 5dc2afedb93c
Revises: 9608bf158b67
Create Date: 2024-02-26 19:20:03.138953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dc2afedb93c'
down_revision: Union[str, None] = '9608bf158b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_data_template',
    sa.Column('task_type_uid', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('field_type', sa.Enum('INT', 'FLOAT', 'STRING', 'DATETIME', name='fieldtypes'), nullable=False),
    sa.Column('is_list', sa.Boolean(), nullable=False),
    sa.Column('load_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_type_uid'], ['task_type.uid'], name=op.f('fk_task_data_template_task_type_uid_task_type')),
    sa.PrimaryKeyConstraint('task_type_uid', 'field_name', 'is_input', name=op.f('pk_task_data_template'))
    )
    op.create_table('task_data',
    sa.Column('task_uid', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.Enum('INTEGER', 'FLOAT', 'STRING', 'DATETIME', name='fieldtypes'), nullable=False),
    sa.Column('field_value', sa.TEXT(), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('is_list', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('load_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_uid'], ['task.uid'], name=op.f('fk_task_data_task_uid_task')),
    sa.PrimaryKeyConstraint('task_uid', 'uid', name=op.f('pk_task_data'))
    )
    op.alter_column('task_type', 'name',
               existing_type=postgresql.ENUM('DOWNLOAD_VIDEO', 'EXTRACT_VIDEO_DESCRIPTION', 'GENERATE_IMAGE_FROM_TEXT', name='tasktypes'),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_type', 'name',
               existing_type=sa.String(length=128),
               type_=postgresql.ENUM('DOWNLOAD_VIDEO', 'EXTRACT_VIDEO_DESCRIPTION', 'GENERATE_IMAGE_FROM_TEXT', name='tasktypes'),
               existing_nullable=False)
    op.drop_table('task_data')
    op.drop_table('task_data_template')
    # ### end Alembic commands ###
