"""init database tables

Revision ID: c7be97eeda5b
Revises: 
Create Date: 2024-02-24 15:55:50.880011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7be97eeda5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('load_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_pipeline')),
    sa.UniqueConstraint('name', name=op.f('uq_pipeline_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline')
    # ### end Alembic commands ###
